import "./globals.css";
import { Libre_Baskerville } from "next/font/google";
import Navigation from "@/components/Navigation";

const libre = Libre_Baskerville({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${libre.className} `}>
        <Navigation />
        {children}
      </body>
    </html>
  );
}
