import "./globals.css";
import { Libre_Baskerville } from "next/font/google";
import Navigation from "@/components/Navigation";
import getArtists from "@/lib/getArtists";

const libre = Libre_Baskerville({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const artists = await getArtists();

  return (
    <html lang="en">
      <body className={`${libre.className} `}>
        <Navigation artists={artists} />
        {children}
      </body>
    </html>
  );
}
